services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    networks:
      - backend
      - dbs
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    networks:
      - backend
      - dbs
  postgres:
    build:
      context: ./db/postgres
      dockerfile: Dockerfile
    networks:
      - dbs
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  backend:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.2.0/24
  dbs:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.3.0/24